# Generated by Django 2.2.5 on 2019-10-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empdata',
            name='Emp_phonNO',
            field=models.IntegerField(default=0),
        ),
    ]
